Redis:
  restart: always
  image: redis:5.0.0
  ports:
    - "6379:6379"
  environment:
    - DEBUG=false

PostgreSQL:
  restart: always
  image: postgres:12.0-alpine
  ports:
    - "5432:5432"
  environment:
    - POSTGRES_PASSWORD=password
    - DEBUG=false
    - POSTGRES_DB=store
